In [13]:
import pandas as pd

In [14]:
data = {'Name':["Aditya", 'Anu','Arsh','Moksh','Himanshu'],'course':['Python DS','Python DS','Python DS','Python Langchain','Python Langchain'],"roll no.":[1,2,3,4,5]}

In [15]:
df1 = pd.DataFrame(data)

In [16]:
df1

       Name            course  roll no.
0    Aditya         Python DS         1
1       Anu         Python DS         2
2      Arsh         Python DS         3
3     Moksh  Python Langchain         4
4  Himanshu  Python Langchain         5

In [17]:
df1.loc[:,"Adm No"] = [45,78,90,34,88]

In [18]:
df1

       Name            course  roll no.  Adm No
0    Aditya         Python DS         1      45
1       Anu         Python DS         2      78
2      Arsh         Python DS         3      90
3     Moksh  Python Langchain         4      34
4  Himanshu  Python Langchain         5      88

In [19]:
values = [12,34,56,78,90]

In [20]:
df1.insert(2,"Marks",value=values)

In [21]:
df1

       Name            course  Marks  roll no.  Adm No
0    Aditya         Python DS     12         1      45
1       Anu         Python DS     34         2      78
2      Arsh         Python DS     56         3      90
3     Moksh  Python Langchain     78         4      34
4  Himanshu  Python Langchain     90         5      88

In [23]:
df2 = pd.DataFrame({'a':[45,56,67],'b':[56,90,67],'c':[23,34,89]})
df3 = pd.DataFrame({'a':[43,22,67],'b':[45,98,32],'c':[11,32,100]})

In [24]:
df2

    a   b   c
0  45  56  23
1  56  90  34
2  67  67  89

In [25]:
df3

    a   b    c
0  43  45   11
1  22  98   32
2  67  32  100

In [29]:
pd.concat([df2,df3], ignore_index=True)

    a   b    c
0  45  56   23
1  56  90   34
2  67  67   89
3  43  45   11
4  22  98   32
5  67  32  100

In [31]:
pd.concat([df2,df3],axis=1)

    a   b   c   a   b    c
0  45  56  23  43  45   11
1  56  90  34  22  98   32
2  67  67  89  67  32  100

In [32]:
df1

       Name            course  Marks  roll no.  Adm No
0    Aditya         Python DS     12         1      45
1       Anu         Python DS     34         2      78
2      Arsh         Python DS     56         3      90
3     Moksh  Python Langchain     78         4      34
4  Himanshu  Python Langchain     90         5      88

In [37]:
df1.sort_values(by='Adm No',ascending =1,ignore_index=True)

       Name            course  Marks  roll no.  Adm No
0     Moksh  Python Langchain     78         4      34
1    Aditya         Python DS     12         1      45
2       Anu         Python DS     34         2      78
3  Himanshu  Python Langchain     90         5      88
4      Arsh         Python DS     56         3      90

In [39]:
for i in df1.iterrows():
    print(i)

(0, Name           Aditya
course      Python DS
Marks              12
roll no.            1
Adm No             45
Name: 0, dtype: object)
(1, Name              Anu
course      Python DS
Marks              34
roll no.            2
Adm No             78
Name: 1, dtype: object)
(2, Name             Arsh
course      Python DS
Marks              56
roll no.            3
Adm No             90
Name: 2, dtype: object)
(3, Name                   Moksh
course      Python Langchain
Marks                     78
roll no.                   4
Adm No                    34
Name: 3, dtype: object)
(4, Name                Himanshu
course      Python Langchain
Marks                     90
roll no.                   5
Adm No                    88
Name: 4, dtype: object)