In [16]:
import pandas as pd

In [17]:
import numpy as np

In [18]:
df1=pd.DataFrame({'Name':['Sourav','Priyanshu','Simran','Anshu',np.nan,'Anurag','Priyanka'],'class':['btech','bca','mca','btech','mcom','mba',np.nan],'Rollno':[34,np.nan,11,10,np.nan,67,89]})
df1

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca     NaN
2     Simran    mca    11.0
3      Anshu  btech    10.0
4        NaN   mcom     NaN
5     Anurag    mba    67.0
6   Priyanka    NaN    89.0

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   class   6 non-null      object
 2   Rollno  5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [20]:
df1.Name.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
Name: Name, dtype: bool

In [21]:
df1.isnull()

    Name  class  Rollno
0  False  False   False
1  False  False    True
2  False  False   False
3  False  False   False
4   True  False    True
5  False  False   False
6  False   True   False

In [22]:
df1.isnull().sum()

Name      1
class     1
Rollno    2
dtype: int64

In [23]:
df1.isna()

    Name  class  Rollno
0  False  False   False
1  False  False    True
2  False  False   False
3  False  False   False
4   True  False    True
5  False  False   False
6  False   True   False

In [24]:
df1.isna().sum()

Name      1
class     1
Rollno    2
dtype: int64

In [25]:
df1

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca     NaN
2     Simran    mca    11.0
3      Anshu  btech    10.0
4        NaN   mcom     NaN
5     Anurag    mba    67.0
6   Priyanka    NaN    89.0

In [ ]:
# df1.loc[df1.isna().index,'class'] = 'btech'
# df1['class'].isna().index

RangeIndex(start=0, stop=7, step=1)

In [34]:
df1['class'].fillna(value= "btech",inplace= True)

In [35]:
df1

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca     NaN
2     Simran    mca    11.0
3      Anshu  btech    10.0
4        NaN   mcom     NaN
5     Anurag    mba    67.0
6   Priyanka  btech    89.0

In [42]:
df1.loc[df1['Rollno'].isna(), 'Rollno'] = 12

In [40]:
df1

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca    12.0
2     Simran    mca    11.0
3      Anshu  btech    10.0
4        NaN   mcom    12.0
5     Anurag    mba    67.0
6   Priyanka  btech    89.0

In [44]:
df2 = pd.DataFrame({'Name' :["Yashree",'Saman','Inder',np.nan,np.nan,'Aditya'], 'marks':[12,np.nan,34,np.nan,89,np.nan], 'course':['python', 'langchain', 'python', np.nan,np.nan,'langchain']})

In [45]:
df2

      Name  marks     course
0  Yashree   12.0     python
1    Saman    NaN  langchain
2    Inder   34.0     python
3      NaN    NaN        NaN
4      NaN   89.0        NaN
5   Aditya    NaN  langchain

In [54]:
df2.loc[0:1,:]

      Name  marks     course
0  Yashree   12.0     python
1    Saman    NaN  langchain

In [55]:
df2.isnull().any()

Name      True
marks     True
course    True
dtype: bool

In [56]:
df2.loc[[1,3,5],'marks'] = 67

In [57]:
df2

      Name  marks     course
0  Yashree   12.0     python
1    Saman   67.0  langchain
2    Inder   34.0     python
3      NaN   67.0        NaN
4      NaN   89.0        NaN
5   Aditya   67.0  langchain

In [58]:
df2.loc[df2.course.isna(),'course'] = 'langchain'

In [59]:
df2

      Name  marks     course
0  Yashree   12.0     python
1    Saman   67.0  langchain
2    Inder   34.0     python
3      NaN   67.0  langchain
4      NaN   89.0  langchain
5   Aditya   67.0  langchain

In [60]:
df2.describe()

           marks
count   6.000000
mean   56.000000
std    27.828043
min    12.000000
25%    42.250000
50%    67.000000
75%    67.000000
max    89.000000

In [61]:
newdf = pd.DataFrame({"Name": ["Arjun", "Kavya", "Riya", "Suresh", "Ravi"], "Department": ["HR", "Finance", "IT", "HR", "Finance"], "Salary": [50000, 60000, 70000, 80000, 90000]})

In [62]:
newdf

     Name Department  Salary
0   Arjun         HR   50000
1   Kavya    Finance   60000
2    Riya         IT   70000
3  Suresh         HR   80000
4    Ravi    Finance   90000

In [63]:
newdf.loc[newdf['Salary'] > 50000, 'Bonus'] = newdf['Salary']*0.1
newdf.loc[newdf['Salary'] <= 50000, 'Bonus'] = newdf['Salary']*0.05

In [64]:
newdf

     Name Department  Salary   Bonus
0   Arjun         HR   50000  2500.0
1   Kavya    Finance   60000  6000.0
2    Riya         IT   70000  7000.0
3  Suresh         HR   80000  8000.0
4    Ravi    Finance   90000  9000.0

In [69]:
df3 = pd.DataFrame({'a':[12,14,13,16,15,21,24]})

In [70]:
df3

    a
0  12
1  14
2  13
3  16
4  15
5  21
6  24

In [71]:
df3.describe()

               a
count   7.000000
mean   16.428571
std     4.429339
min    12.000000
25%    13.500000
50%    15.000000
75%    18.500000
max    24.000000

In [ ]:
# 12,14,13,16,15,21,24
# n = 7
# 12,13,14,15,16,21,24


# 25/100 *(n-1) +1 = 2.5



13 + (14-13)*0.5

13.5