In [1]:
import pandas as pd

In [2]:
df  = pd.read_csv('pre-owned cars.csv')

In [3]:
df

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,01-08-2022,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,01-07-2021,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2801,Ford,Ecosport TREND + 1.5L PETROL AT,Automatic,2018.0,NaN,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT
2802,Honda,Jazz 1.2L I-VTEC V,Manual,2015.0,NaN,Petrol,1199.0,38706.0,2nd owner,412000,8057.0,True,Yes,MH01,2015 Honda Jazz 1.2L I-VTEC V
2803,Hyundai,Elite i20 MAGNA 1.2,Manual,2016.0,NaN,Petrol,1197.0,31405.0,1st owner,496000,9704.0,True,Yes,MH03,2016 Hyundai Elite i20 MAGNA 1.2
2804,Maruti,Baleno DELTA PETROL 1.2,Manual,2017.0,NaN,Petrol,1197.0,47676.0,1st owner,509000,9959.0,True,Yes,MH04,2017 Maruti Baleno DELTA PETROL 1.2
2805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1883558000,NaN,NaN,NaN,NaN,NaN

In [4]:
#head, tail

In [6]:
df.head(10)

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,01-08-2022,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,01-07-2021,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL
5,Honda,WR-V 1.2L I-VTEC VX MT,Manual,2021.0,01-10-2021,Petrol,1199.0,44787.0,1st owner,796000,15561.0,True,No,UP32,2021 Honda WR-V 1.2L I-VTEC VX MT
6,Tata,PUNCH CREATIVE 1.2 RTN DUAL TONE,Manual,2022.0,01-11-2022,Petrol,1199.0,450.0,1st owner,813000,15475.0,True,Yes,DL3C,2022 Tata PUNCH CREATIVE 1.2 RTN DUAL TONE
7,Tata,NEXON XMA DIESEL,Automatic,2020.0,01-02-2021,Diesel,NaN,59866.0,1st owner,728000,14228.0,True,No,DL5C,2020 Tata NEXON XMA DIESEL
8,Mahindra,XUV700 AX 7 LUXURY D AWD AT 7 STR,Automatic,2022.0,01-04-2022,Diesel,2184.0,62567.0,1st owner,2322000,44197.0,True,No,DL10,2022 Mahindra XUV700 AX 7 LUXURY D AWD AT 7 STR
9,Ford,Ecosport TITANIUM + 1.5L PETROL AT,Automatic,2019.0,01-07-2019,Petrol,1497.0,58503.0,1st owner,766000,14977.0,True,No,DL10,2019 Ford Ecosport TITANIUM + 1.5L PETROL AT

In [8]:
df.tail(10)

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
2796,Hyundai,Verna FLUIDIC 4S 1.6 VTVT S,Manual,2015.0,NaN,Petrol,1591.0,32750.0,1st owner,490000,9587.0,True,No,MH47,2015 Hyundai Verna FLUIDIC 4S 1.6 VTVT S
2797,Hyundai,NEW I20 ASTA 1.2 AT,Automatic,2021.0,NaN,Petrol,1197.0,15831.0,1st owner,831000,15817.0,True,Yes,MH05,2021 Hyundai NEW I20 ASTA 1.2 AT
2798,Hyundai,NEW SANTRO SPORTZ AMT,Automatic,2019.0,NaN,Petrol,1086.0,56370.0,2nd owner,396000,7732.0,True,Yes,MH48,2019 Hyundai NEW SANTRO SPORTZ AMT
2799,Maruti,IGNIS DELTA 1.2 AMT,Automatic,2017.0,NaN,Petrol,1197.0,80035.0,1st owner,428000,8377.0,True,No,MH01,2017 Maruti IGNIS DELTA 1.2 AMT
2800,Honda,Brio S MT,Manual,2013.0,NaN,Petrol,1198.0,96363.0,2nd owner,213000,5614.0,True,Yes,MH01,2013 Honda Brio S MT
2801,Ford,Ecosport TREND + 1.5L PETROL AT,Automatic,2018.0,NaN,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT
2802,Honda,Jazz 1.2L I-VTEC V,Manual,2015.0,NaN,Petrol,1199.0,38706.0,2nd owner,412000,8057.0,True,Yes,MH01,2015 Honda Jazz 1.2L I-VTEC V
2803,Hyundai,Elite i20 MAGNA 1.2,Manual,2016.0,NaN,Petrol,1197.0,31405.0,1st owner,496000,9704.0,True,Yes,MH03,2016 Hyundai Elite i20 MAGNA 1.2
2804,Maruti,Baleno DELTA PETROL 1.2,Manual,2017.0,NaN,Petrol,1197.0,47676.0,1st owner,509000,9959.0,True,Yes,MH04,2017 Maruti Baleno DELTA PETROL 1.2
2805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1883558000,NaN,NaN,NaN,NaN,NaN

In [9]:
df.columns

Index(['brand', 'model', 'transmission', 'make_year', 'reg_year', 'fuel_type',
       'engine_capacity(CC)', 'km_driven', 'ownership', 'price',
       'overall_cost', 'has_insurance', 'spare_key', 'reg_number', 'title'],
      dtype='object')

In [10]:
df.shape

(2806, 15)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2806 entries, 0 to 2805
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                2805 non-null   object
 1   model                2805 non-null   object
 2   transmission         2805 non-null   object
 3   make_year            2805 non-null   float64
 4   reg_year             720 non-null    object
 5   fuel_type            2805 non-null   object
 6   engine_capacity(CC)  2688 non-null   float64
 7   km_driven            2805 non-null   float64
 8   ownership            2805 non-null   object
 9   price                2806 non-null   int64
 10  overall_cost         2805 non-null   float64
 11  has_insurance        2805 non-null   object
 12  spare_key            2805 non-null   object
 13  reg_number           2805 non-null   object
 14  title                2805 non-null   object
dtypes: float64(4), int64(1), object(10)
memory usage: 329.0+ KB

In [12]:
df.reg_year.isnull().sum()

2086

In [13]:
df.describe()

,make_year,engine_capacity(CC),km_driven,price,overall_cost
count,2805.000000,2688.000000,2805.000000,2.806000e+03,2805.000000
mean,2018.181105,1259.027530,49215.477362,1.342522e+06,13495.022816
std,2.945293,254.504798,26626.932696,3.554669e+07,6040.809220
min,2010.000000,624.000000,450.000000,1.630000e+05,4039.000000
25%,2016.000000,1194.000000,28540.000000,4.350000e+05,9267.000000
50%,2018.000000,1197.000000,45695.000000,5.940000e+05,12145.000000
75%,2021.000000,1462.000000,68182.000000,8.140000e+05,15760.000000
max,2024.000000,2694.000000,143991.000000,1.883558e+09,47338.000000

In [14]:
df.head()

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,01-01-2021,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,01-07-2018,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,01-08-2022,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,01-07-2021,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL

In [15]:
df.brand.value_counts()

brand
Maruti        925
Hyundai       660
Honda         276
Tata          240
Renault       167
KIA           116
Mahindra      114
Ford           64
Volkswagen     53
Nissan         38
MG             37
Toyota         36
Datsun         34
Skoda          33
Jeep           12
Name: count, dtype: int64

In [16]:
df.loc[df.loc[:,'transmission'] == 'Automatic']

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,01-04-2023,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
7,Tata,NEXON XMA DIESEL,Automatic,2020.0,01-02-2021,Diesel,NaN,59866.0,1st owner,728000,14228.0,True,No,DL5C,2020 Tata NEXON XMA DIESEL
8,Mahindra,XUV700 AX 7 LUXURY D AWD AT 7 STR,Automatic,2022.0,01-04-2022,Diesel,2184.0,62567.0,1st owner,2322000,44197.0,True,No,DL10,2022 Mahindra XUV700 AX 7 LUXURY D AWD AT 7 STR
9,Ford,Ecosport TITANIUM + 1.5L PETROL AT,Automatic,2019.0,01-07-2019,Petrol,1497.0,58503.0,1st owner,766000,14977.0,True,No,DL10,2019 Ford Ecosport TITANIUM + 1.5L PETROL AT
16,Maruti,Alto K10 VXI AMT,Automatic,2014.0,01-02-2015,Petrol,998.0,71297.0,1st owner,265000,5901.0,True,No,DL3C,2014 Maruti Alto K10 VXI AMT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,Tata,NEXON FEARLESS + SUNROOF DCA DUAL TONE 1.2 PETROL,Automatic,2024.0,NaN,Petrol,NaN,11540.0,1st owner,1399000,26629.0,True,Yes,MH46,2024 Tata NEXON FEARLESS + SUNROOF DCA DUAL TO...
2797,Hyundai,NEW I20 ASTA 1.2 AT,Automatic,2021.0,NaN,Petrol,1197.0,15831.0,1st owner,831000,15817.0,True,Yes,MH05,2021 Hyundai NEW I20 ASTA 1.2 AT
2798,Hyundai,NEW SANTRO SPORTZ AMT,Automatic,2019.0,NaN,Petrol,1086.0,56370.0,2nd owner,396000,7732.0,True,Yes,MH48,2019 Hyundai NEW SANTRO SPORTZ AMT
2799,Maruti,IGNIS DELTA 1.2 AMT,Automatic,2017.0,NaN,Petrol,1197.0,80035.0,1st owner,428000,8377.0,True,No,MH01,2017 Maruti IGNIS DELTA 1.2 AMT
2801,Ford,Ecosport TREND + 1.5L PETROL AT,Automatic,2018.0,NaN,Petrol,1497.0,46982.0,1st owner,661000,12920.0,True,Yes,MH03,2018 Ford Ecosport TREND + 1.5L PETROL AT

In [ ]:
df.fuel_type.value_counts()

fuel_type
Petrol      2373
Diesel       318
CNG          110
Electric       4
Name: count, dtype: int64

In [20]:
df.loc[(df.loc[:,'transmission'] == 'Automatic')     &    (df.loc[:,'fuel_type'] == 'Diesel' )]

,brand,model,transmission,make_year,reg_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
7,Tata,NEXON XMA DIESEL,Automatic,2020.0,01-02-2021,Diesel,NaN,59866.0,1st owner,728000,14228.0,True,No,DL5C,2020 Tata NEXON XMA DIESEL
8,Mahindra,XUV700 AX 7 LUXURY D AWD AT 7 STR,Automatic,2022.0,01-04-2022,Diesel,2184.0,62567.0,1st owner,2322000,44197.0,True,No,DL10,2022 Mahindra XUV700 AX 7 LUXURY D AWD AT 7 STR
31,KIA,CARENS LUXURY PLUS 1.5 DIESEL AT 7 STR,Automatic,2022.0,01-12-2022,Diesel,1493.0,34694.0,1st owner,1654000,31482.0,True,No,HR36,2022 KIA CARENS LUXURY PLUS 1.5 DIESEL AT 7 STR
38,Mahindra,XUV500 W7 AT,Automatic,2021.0,01-04-2021,Diesel,2179.0,25366.0,1st owner,1400000,26644.0,True,No,HR29,2021 Mahindra XUV500 W7 AT
86,Maruti,Vitara Brezza VDI AMT,Automatic,2019.0,01-10-2019,Diesel,1248.0,86677.0,1st owner,632000,14068.0,True,Yes,DL9C,2019 Maruti Vitara Brezza VDI AMT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2639,Mahindra,XUV500 W10 AT,Automatic,2017.0,NaN,Diesel,2179.0,82030.0,1st owner,1015000,19320.0,True,No,MH43,2017 Mahindra XUV500 W10 AT
2652,Hyundai,Creta SX PLUS AT 1.6 DIESEL,Automatic,2015.0,NaN,Diesel,1582.0,112672.0,1st owner,778000,17298.0,True,No,MH04,2015 Hyundai Creta SX PLUS AT 1.6 DIESEL
2677,Tata,NEXON XZA PLUS DIESEL,Automatic,2019.0,NaN,Diesel,1497.0,39565.0,1st owner,926000,17627.0,True,No,MH01,2019 Tata NEXON XZA PLUS DIESEL
2777,Volkswagen,Ameo HIGHLINE PLUS 1.5L AT 16 ALLOY,Automatic,2017.0,NaN,Diesel,1498.0,86674.0,1st owner,537000,10497.0,True,Yes,MH01,2017 Volkswagen Ameo HIGHLINE PLUS 1.5L AT 16 ...
2792,Mahindra,TUV300 T8 AMT,Automatic,2016.0,NaN,Diesel,1493.0,44459.0,1st owner,641000,12537.0,True,No,MH43,2016 Mahindra TUV300 T8 AMT

In [22]:

df.drop('reg_year',axis=1,inplace=True)

In [23]:
df.head()

,brand,model,transmission,make_year,fuel_type,engine_capacity(CC),km_driven,ownership,price,overall_cost,has_insurance,spare_key,reg_number,title
0,Mahindra,Thar LX D 4WD MT CONVERTIBLE,Manual,2020.0,Diesel,2184.0,11003.0,1st owner,1231000,23431.0,True,No,HR26,2020 Mahindra Thar LX D 4WD MT CONVERTIBLE
1,Hyundai,Verna 1.6 VTVT SX,Manual,2018.0,Petrol,1591.0,66936.0,1st owner,786000,15359.0,True,No,DL7C,2018 Hyundai Verna 1.6 VTVT SX
2,Tata,Harrier XT PLUS 2.0L KRYOTEC DARK EDITON,Manual,2022.0,Diesel,1956.0,27990.0,1st owner,1489000,28349.0,True,No,HR29,2022 Tata Harrier XT PLUS 2.0L KRYOTEC DARK ED...
3,Honda,City 1.5L I-VTE V CVT,Automatic,2023.0,Petrol,1498.0,5061.0,1st owner,1227000,23355.0,True,Yes,DL4C,2023 Honda City 1.5L I-VTE V CVT
4,Ford,Ecosport TITANIUM 1.5L DIESEL,Manual,2021.0,Diesel,1498.0,23480.0,1st owner,887000,16883.0,True,No,UP14,2021 Ford Ecosport TITANIUM 1.5L DIESEL

In [24]:
df.to_csv('new.csv')